/** Common B2B export destinations for inquiry form */
export const INQUIRY_COUNTRIES = [
  'United States',
  'United Kingdom',
  'United Arab Emirates',
  'Saudi Arabia',
  'Australia',
  'Canada',
  'Germany',
  'France',
  'Spain',
  'Italy',
  'Netherlands',
  'Mexico',
  'Brazil',
  'Russia',
  'South Africa',
  'Nigeria',
  'India',
  'Thailand',
  'Vietnam',
  'Indonesia',
  'Philippines',
  'Malaysia',
  'Japan',
  'South Korea',
  'Qatar',
  'Kuwait',
  'Oman',
  'Turkey',
  'Poland',
  'Sweden',
  'Norway',
  'Other'
] as const;
